<Project>

  <PropertyGroup>
    <ProductName>Qowaiv Domain Model</ProductName>
    <Description>Qowaiv implements common, universal domain objects. These types form the base of your domain model.</Description>
    <Authors>
      <![CDATA[
Corniel Nobel;
Jack Kester;
Jur Balledux;
Marcel Strik;
Patrick Evers
]]>
    </Authors>
    <Owners>Qowaiv community</Owners>
    <PackageTags>qowaiv domain model</PackageTags>
    <Company>Qowaiv community</Company>
    <Copyright>Copyright © Qowaiv community 2013-current</Copyright>
    <LangVersion>14.0</LangVersion>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <NuGetAuditMode>all</NuGetAuditMode>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Label="Signing">
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)/build/Qowaiv.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ContinuousIntegrationBuild)' == 'true'">
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>

</Project>
