<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="coverlet.collector" Version="8.0.0" />

    <PackageVersion Include="DotNetProjectFile.Analyzers.Sdk" Version="1.9.0" />
    <PackageVersion Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="Microsoft.Sbom.Targets" Version="4.1.2" />
    <PackageVersion Include="NUnit" Version="4.5.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.1.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageVersion Include="Qowaiv" Version="8.0.0" />
    <PackageVersion Include="Qowaiv.Analyzers.CSharp" Version="2.1.0" />
    <PackageVersion Include="Qowaiv.TestTools" Version="8.0.0" />
    <PackageVersion Include="Qowaiv.Validation.Abstractions" Version="2.0.0" />
    <PackageVersion Include="Qowaiv.Validation.Fluent" Version="3.0.0" />
    <PackageVersion Include="Qowaiv.Validation.Guarding" Version="2.0.0" />
    <PackageVersion Include="Qowaiv.Validation.Messages" Version="2.0.0" />
    <PackageVersion Include="Qowaiv.Validation.TestTools" Version="3.0.0" />
    <PackageVersion Include="StyleCop.Analyzers.Unstable" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="AsyncFixer" Version="2.1.0" />
    <GlobalPackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.2" />
    <GlobalPackageReference Include="DotNetProjectFile.Analyzers" Version="1.9.0" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.200" />
    <GlobalPackageReference Include="PolySharp" Version="1.15.0" />
    <GlobalPackageReference Include="Qowaiv.CodeGeneration.SingleValueObjects" Version="1.1.5" />
    <GlobalPackageReference Include="Qowaiv.Diagnostics.Contracts" Version="2.0.6" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.20.0.135146" />
  </ItemGroup>
</Project>
