global using ConquerClub.Domain.Commands;
global using ConquerClub.Domain.Events;
global using ConquerClub.Domain.Validation;
global using MathNet.Numerics.Random;
global using Qowaiv.DomainModel;
global using Qowaiv.Validation.Abstractions;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Linq;
global using ContinentId = Qowaiv.Identifiers.Id<ConquerClub.Domain.ForContinent>;
global using CountryId = Qowaiv.Identifiers.Id<ConquerClub.Domain.ForCountry>;
global using GameId = Qowaiv.Identifiers.Id<ConquerClub.Domain.ForGame>;
