global using ConquerClub.Domain;
global using ConquerClub.Domain.Commands;
global using ConquerClub.Domain.Events;
global using ConquerClub.Domain.Handlers;
global using FluentAssertions;
global using MathNet.Numerics.Random;
global using NUnit.Framework;
global using Qowaiv.DomainModel;
global using Qowaiv.DomainModel.Commands;
global using Qowaiv.Validation.Abstractions;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using CountryId = Qowaiv.Identifiers.Id<ConquerClub.Domain.ForCountry>;
global using GameId = Qowaiv.Identifiers.Id<ConquerClub.Domain.ForGame>;
