//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquerClub.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquerClub.Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country with id {0} does not exist..
        /// </summary>
        internal static string CountryMustExist {
            get {
                return ResourceManager.GetString("CountryMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} does not have any country..
        /// </summary>
        internal static string MusHaveCountry {
            get {
                return ResourceManager.GetString("MusHaveCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action can only be applied by the active {0}, not by {1}..
        /// </summary>
        internal static string MustBeActive {
            get {
                return ResourceManager.GetString("MustBeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action must be in the {0} phase to be executed, not in the {1} phase..
        /// </summary>
        internal static string MustBeInPhase {
            get {
                return ResourceManager.GetString("MustBeInPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country {0} must be owned by {1}..
        /// </summary>
        internal static string MustBeOwnedBy {
            get {
                return ResourceManager.GetString("MustBeOwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} can not be reached from {0}..
        /// </summary>
        internal static string MustBeReachable {
            get {
                return ResourceManager.GetString("MustBeReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County {0} lacks an army to attack..
        /// </summary>
        internal static string MustHaveArmiesToAttack {
            get {
                return ResourceManager.GetString("MustHaveArmiesToAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country {0} must not be owned by {1}..
        /// </summary>
        internal static string MustNotBeOwnedBy {
            get {
                return ResourceManager.GetString("MustNotBeOwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not be executed as it requires more armies ({1}) then available ({0})..
        /// </summary>
        internal static string MustNotExeedArmyBuffer {
            get {
                return ResourceManager.GetString("MustNotExeedArmyBuffer", resourceCulture);
            }
        }
    }
}
