name: .NET 7.0 Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Test with .NET
      run: dotnet test --configuration Release
