name: .NET 9.0 Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Test with .NET
      run: dotnet test Qowaiv.DomainModel.sln  --configuration Release
